image: node:10

stages:
- build
- test

build_lib:
    stage: build
    script:
    - npm install
    - npm run lint
    - npm run build
    artifacts:
        paths:
        - dist
        - lib
    cache:
        key: "$CI_JOB_STAGE"
        paths:
        - node_modules/

build_doc:
    stage: build
    script:
    - npm install
    - npm run docs:build
    artifacts:
        paths:
        - typedoc
    cache:
        key: "$CI_JOB_STAGE"
        paths:
        - node_modules/

test_lib:
    stage: test
    script:
    - npm install
    - npm run test:lib
    cache:
        key: "$CI_JOB_STAGE"
        paths:
        - node_modules/

test_plugins:
    stage: test
    script:
    - npm install
    - npm run test:plugins
    cache:
        key: "$CI_JOB_STAGE"
        paths:
        - node_modules/
