name: Continous Integration

on: [ push, pull_request ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@tmorin'
      # build
      - name: Install dependencies
        run: npm ci
      - name: Lint sources
        run: npm run lint
      - name: Build sources
        run: npm run build
      - name: Test library
        run: npm run test:lib
        env:
          SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
          SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
      - name: Test plugins
        run: npm run test:plugins
      - name: Build documentation
        run: npm run docs:build
      # publication
      - name: Publish package
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: npm publish --tag latest
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Publish documentation
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./typedoc
