name: Integration

on:
  push:
    branches:
      - '**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@tmorin'
      - name: install dependencies
        run: npm ci
      - name: lint sources
        run: npm run lint
      - name: build sources
        run: npm run build
      - name: test library
        run: npm run test:lib
        env:
          SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
          SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
      - name: test plugins
        run: npm run test:plugins
      - name: build documentation
        run: npm run docs:build
